bnb-chain/node

- app/app.go
- app/config/config.go
- asset/testnet/app.toml
- common/upgrade/upgrade.go
- integration_test.sh
- plugins/dex/list/handler.go
- plugins/dex/order/handler.go
BNB Beacon Chain’s primary focus, its native decentralized application ("dApp") BNB DEX, has demonstrated its low-latency matching with large capacity headroom. With the development of BNB Smart Chain and AMM-based decentralized exchanges running well on it, BNB DEX has less usage and liquidity. After implementing this BEP, the DEX module will be disabled, which will give Beacon Chain more computing power for the future computing and governance focuses.
BNB Beacon Chain(BC) is a blockchain developed by the BNB Chain community that implements a vision of a decentralized exchange (DEX) for digital assets. The heart of Beacon Chain is a highly performant matching engine built on distributed consensus that aims to replicate the < 1 second trading efficiency of current centralized exchanges. …
> [R4R]feat: decommission decentralized exchange on BNB Beacon Chain

- CHANGELOG.md
- app/app.go
- app/config/config.go
- asset/testnet/app.toml
- common/upgrade/upgrade.go
- plugins/dex/list/handler.go
- plugins/dex/order/handler.go
- version/version.go
This pr includes the changes for v0.10.0 release. Please refer Changes section for details.
Decommission Decentralized Exchange on BNB Beacon Chain.
n/a
* [\#875](https://github.com/bnb-chain/node/pull/875) [DEX] Implement BEP151
> [R4R] prepare for release v0.10.0

- .github/workflows/docker-release.yml
- Dockerfile
- asset/mainnet/app.toml
- asset/testnet/app.toml
- asset/testnet/config.toml
- docker-entrypoint.sh
- docs/docker.md
1. Automatically upload the latest version of Docker Image to GitHub package when a new version is released
2. Fix dockerfile to make sure images work
N/A
```
docker run -p 27146:27146 -p 27147:27147 -e NETWORK=testnet ghcr.io/bnb-chain/node:latest
```
N/A
N/A
N/A
> [R4R]fix the dockerfile and add ci script to docker image

- CHANGELOG.md
- asset/mainnet/app.toml
- version/version.go
This release is to add activation height of [BEP-151](https://github.com/bnb-chain/BEPs/blob/master/BEP151.md) on Mainnet.
BEP-151 proposes to securely and smoothly decommission the build-in decentralized exchange on BNB Beacon Chain.
The activation height is 264000000, which will be approximately happened at 2 Sep 2022 06:00 UTC.
No
...
No
> Prepare for release v0.10.1: Add BEP-151 Mainnet Height

- app/app.go
- app/config/config.go
- asset/testnet/app.toml
- common/upgrade/upgrade.go
- go.mod
- go.sum
In some scenarios, the community may need a proposal that does not directly cause any changes, like agreeing to a certain strategy, plan, commitment or other statement.
Right now, there are many system parameters that control the behavior of the BSC, e.g. slash amount, cross-chain transfer fees. All these parameters can be determined by the BSC Validator Set together through a proposal-vote process based on staking. The process executes on the BC and the new parameter values will be picked up by either the management module on the BC or corresponding system contracts via the cross-chain communication protocol. The proposals can be classified into two groups: 
1. Param Change Proposal if the parameter takes effect on the Beacon Chain; 
2. Cross Param Change Proposal if the parameter takes …
> bep173: enable text proposal on BNB Smart Chain

- README.md
`make install` instead of `make build`
Just running `make build` will not make the `bnbcli` command to run. `make install` will install it and then `bnbcli` will run fine.
tell us why we need these changes...
add an example CLI or API response...
* add each change in a bullet point here
* ...
...
> Install command for cli tool

- .github/workflows/docker-release.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/integration.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
Some GitHub action tools will no longer be supported soon. Update these tools to ensure that CI can normally work in the future.
1. `ubuntu-18.04` => `ubuntu-latest`
2. `macos-11` => `macos-latest`
3. `windows-2019` => `windows-latest`
4. `actions/checkout@v2` => `actions/checkout@v3`
5. `actions/setup-go@v2` => `actions/setup-go@v3`
6. `actions/cache@v2` => `actions/cache@v3`
7. `actions/upload-artifact@v2` => `actions/upload-artifact@v3`
8. `actions/download-artifact@v2` => `actions/download-artifact@v3`
9. `actions/create-release@latest`, `actions/upload-release-asset@v1` => `softprops/action-gh-release@v1`
N/A
* ci
> ci: update unmaintained tools to use maintained tools

- CHANGELOG.md
- asset/testnet/app.toml
- version/version.go
This is a hardfork release to enable BEP159 on testnet
FEATURES
* [\#880](https://github.com/bnb-chain/node/pull/880) [BEP] BEP-159: Introduce A New Staking Mechanism on BNB Beacon Chain
IMPROVEMENT
* [\#899](https://github.com/bnb-chain/node/pull/899) [ci] update unmaintained tools to use maintained tools
BUG FIX
* [\#897](https://github.com/bnb-chain/node/pull/897) [fix] add bsc chainID to encodeSigHeader when submitting evidence for slashing
No.
The breaking double sign issue is fixed in this release as well.
NO
> release: prepare for release v0.10.4

- app/app.go
the cross stake channel didn't be registered on a right way.
N/A
N/A
* add cross stake channel register every time the app init after BEP153 upgrade
* https://github.com/bnb-chain/node/issues/898
> fix: register cross stake channel after node restart

- CHANGELOG.md
- version/version.go
This is a release for issue fix
BUG FIX
* [\#8904](https://github.com/bnb-chain/node/pull/8904) [fix] register cross stake channel after node restart
N/A
Add cross stake channel register at node init
https://github.com/bnb-chain/node/issues/898
> release: prepare for release v0.10.5

- CHANGELOG.md
- app/app.go
- asset/testnet/app.toml
- version/version.go
This is a bug fix release for a critical issue that the node may fail to reach a consensus state after a restart.
BUG FIX
* [\#8904](https://github.com/bnb-chain/node/pull/8904) [fix] register cross-stake channel after node restart
N/A
Add cross stake channel register at node init
https://github.com/bnb-chain/node/issues/898
> prepare for release v0.10.5

- README.md
The current readme is totally out of date, this PR fix it.
The following update is made in this PR:
1. Dex-related chapter is removed.
2. Fix the not working CLI tutorial.
3. Adding more futures.
No
Document fix.
> docs: update the readme to latest working one

- CHANGELOG.md
- version/version.go
This is a release for code improvement
IMPROVEMENT
* [\#908](https://github.com/bnb-chain/node/pull/908) [docs] update the readme to latest working one
* [\#907](https://github.com/bnb-chain/node/pull/907) [fix] remove bnb-chain go-sdk dep
N/A
N/A
> release: prepare for release v0.10.6

- asset/mainnet/app.toml
- asset/testnet/app.toml
Add LimitConsAddrUpdateIntervalHeight and BEP159Height in Mainnet and LimitConsAddrUpdateIntervalHeight in Testnet to activate the hardfork.
The approximate time of Testnet height   36174050  is `2023-02-15T06:00:00`.
The approximate time of Mainnet height 298721375 is `2023-02-24T06:00:00`.
> config: add LimitConsAddrUpdateIntervalHeight and BEP159Height in asset

- CHANGELOG.md
- version/version.go
This is a hard-fork release, with improvements and bug fixes.
For the hard-fork height on testnet and mainnet, please refer to https://github.com/bnb-chain/node/pull/921
FEATURES
* [\#921](https://github.com/bnb-chain/node/pull/921) [config] add LimitConsAddrUpdateIntervalHeight and BEP159Height in assets
* [\#917](https://github.com/bnb-chain/node/pull/917) [Staking] limit sidechain consensus addr update interval
IMPROVEMENT
* [\#919](https://github.com/bnb-chain/node/pull/919) [deps] bump cosmos-sdk to v0.25.8
* [\#915](https://github.com/bnb-chain/node/pull/915) [deps] update deps that were reported in OSV issues
BUG FIX
* [\#914](https://github.com/bnb-chain/node/pull/914) [fix] fix bnbcli params side-params error
N/A
N/A
> release: prepare for release v0.10.7

- app/config/config.go
- asset/mainnet/app.toml
- asset/testnet/app.toml
- cmd/gen_devnet/main.go
- scripts/bep159_integration_test.sh
The BEP159 hard fork still needs more discussion with the community, this PR removes it from the code first.
The BSC validator set maintainers need more time discussion about BEP159, especially the reward ratio. The team decide to delay the upgrade of BEP159
None
None
...
> revert: remove the hardfork height of BEP159Height on mainnet

- cmd/bnbcli/main.go
- cmd/bnbcli/utils/consensus_key.go
- cmd/bnbcli/utils/root.go
Add a command to generate the JSON file containing the private key to use as a validator in the consensus protocol.
The generated file can be used as the `priv_validator_key_file` in `config.toml`. And the output consensus pubkey in bech32 format can be used as the parameter `pubkey` in `bnbcli staking create-validator-open` command.
```toml
priv_validator_key_file = "config/priv_validator_key.json"
```
Currently, the consensus key is generated in the command `bnbchaind init`.
Generate the consensus key separately can be used when:
1. Users want to `create-validator` first and then init the full node.
2. Users want to update the consensus key.
```bash
$ ./build/bnbcli utils gen-consensus-key -h
generate the JSON file containing the private key to use as a validator in the consensus …
```
> feat: add gen-consensus-key command in bnbcli

- CHANGELOG.md
- version/version.go
This pr will prepare for the release v0.10.9 to change the version of node.
Change the version of node.
N/A
* change the version of node
> release: prepare for release v0.10.9

- CHANGELOG.md
- version/version.go
This release will bumps version of cosmos-sdk to v0.26.1 which will fix the issue introduced by https://github.com/bnb-chain/bnc-cosmos-sdk/pull/320.
Bumps version of cosmos-sdk the fix the bug.
N/A
* [\#930](https://github.com/bnb-chain/node/pull/930) [deps] deps: bump cosmos-sdk to v0.26.1
> release: draft the release v0.10.9 

- CHANGELOG.md
- asset/mainnet/app.toml
- version/version.go
This pr will enable the upgrade of [BEP171](https://github.com/bnb-chain/BEPs/pull/171) on mainnet. 
The forecasted upgrade time is 21th Apr. at 7:00 (UTC).
Enable BEP171.
NA
* `app.toml`
> feat: enable bep171 upgrade on mainnet

- CHANGELOG.md
- version/version.go
This drafts the release of v0.10.11, which is a bug fix release.
BUG FIX
* [\#942](https://github.com/bnb-chain/node/pull/942) [deps] deps: bump cosmos-sdk to v0.26.2
Bug fix of cli client
```
/tbnbcli token info --symbol TCO-FC2 --chain-id=Binance-Chain-Ganges --node=data-seed-pre-0-s3.binance.org:80
ERROR: failed to prove merkle absence proof: Calculated root hash is invalid: expected [161 49 185 8 105 55 181 121 32 243 235 71 68 181 82 167 160 27 12 241 144 19 162 158 46 98 194 202 246 243 49 169] but got [39 141 219 74 147 43 56 167 105 71 172 202 68 173 171 108 109 124 101 138 17 151 247 201 119 103 250 236 190 16 28 228]
```
```
❯ ./tbnbcli token info --symbol BUSD-BAF --chain-id=Binance-Chain-Ganges --node=data-seed-pre-0-s3.binance.org:80
{
"type": "bnbchain/Token",
"value": { …
```
> release: draft release v0.10.11

- CHANGELOG.md
- version/version.go
This pr prepares the release of v0.10.13.
[\#950](https://github.com/bnb-chain/node/pull/950) [deps] fix: bump cosmos sdk to fix validator unmarshal issue
Release
NA
* change log
> docs: update change log to release v0.10.13

- cmd/bnbchaind/init/collect_gentxs.go
support setting acc prefix  when collecting gentxs
useful to deploy test network.
add an example CLI or API response...
* add each change in a bullet point here
* ...
...
> Support setting acc prefix  when collecting gentxs

- CHANGELOG.md
- version/version.go
support setting acc prefix when collecting gentxs
tell us why we need these changes...
add an example CLI or API response...
* add each change in a bullet point here
* ...
...
> support setting acc prefix when collecting gentxs

- CHANGELOG.md
- asset/mainnet/app.toml
- version/version.go
This pr prepares the release v0.10.14, with new features and bug fixes. 
The BNB Beacon Chain mainnet is expected to have a scheduled hard fork upgrade at block height 321213000. Based on the current block generation speed, the hard fork is forecasted to occur on 15th Jun. at 6:00 (UTC). The full node runners on mainnet must switch their software version to [v0.10.14](https://github.com/bnb-echain/node/releases/tag/v0.10.14) by 15th Jun.
Be noted: [BEP126](https://github.com/bnb-chain/BEPs/blob/master/BEP126.md) will be enabled for mainnet in this release.
* [\#953](https://github.com/bnb-chain/node/pull/953) [cli] feat:support setting acc prefix when collecting gentxs
* [\#957](https://github.com/bnb-chain/node/pull/957) [deps] deps: bump cosmos-sdk to v0.26.5
Release
NA
Notable changes: …
> release: prepare change log for release v0.10.14

- CHANGELOG.md
- asset/testnet/app.toml
- go.mod
- go.sum
- version/version.go
This pr prepares the release v0.10.15, with new features and bug fixes. 
The BNB Beacon Chain *testnet* is expected to have a scheduled hard fork upgrade at block height 41650000. Based on the current block generation speed, the hard fork is forecasted to occur on 11th Jul. at 6:00 (UTC). The full node runners on *testnet* must switch their software version to [v0.10.15](https://github.com/bnb-echain/node/releases/tag/v0.10.15) before the height.
Be noted: [BEP255](https://github.com/bnb-chain/BEPs/blob/master/BEP255.md) will be enabled for *testnet* in this release.
Release
NA
* change log
* testnet asset
> release: update change log and version for release v0.10.15

- CHANGELOG.md
- asset/mainnet/app.toml
- version/version.go
The BNB Beacon Chain *mainnet* is expected to have a scheduled hard fork upgrade at block height 328088888. Based on the current block generation speed, the hard fork is forecasted to occur on 19th Jul. at 6:00 (UTC). The full node runners on *mainnet* must switch their software version to [v0.10.16](https://github.com/bnb-echain/node/releases/tag/v0.10.16) or higher version before the height.
Add bep255 upgrade height for mainnet
NA
* add bep255 upgrade height for mainnet
> asset: add bep255 upgrade height for mainnet

- CHANGELOG.md
- asset/mainnet/app.toml
- version/version.go
This pr drafts the release v0.10.16, which will enable BEP255 upgrade on mainnet. For more information, please refer to [BEP255](https://github.com/bnb-chain/BEPs/blob/master/BEP255.md).
The BNB Beacon Chain *mainnet* is expected to have a scheduled hard fork upgrade at block height 328088888. Based on the current block generation speed, the hard fork is forecasted to occur on 19th Jul. at 6:00 (UTC). The full node runners on *mainnet* must switch their software version to [v0.10.16](https://github.com/bnb-echain/node/releases/tag/v0.10.16) before the height.
Release
NA
* change log
* mainnet asset
> release: draft release for v0.10.16

- plugins/tokens/plugin.go
- plugins/tokens/timelock/handler.go
- plugins/tokens/timelock/keeper.go
- plugins/tokens/timelock/keeper_test.go
this pr include 2 fix for refund:
1. [only refund opened swap](https://github.com/bnb-chain/node/commit/dad1e235f7e016765ed4ac6de2b4236f9e150f4d)
2. [do not check timelock time if isBCFusionRefund](https://github.com/bnb-chain/node/commit/587060ad41f19e88f717a970ec1d49c59228ceec)
n/a
n/a
* refund
- [ x manual transaction test passed (cli invoke)
n/a
n/a
> fix: refund swap, timelock failed

- go.mod
- go.sum
chore: update cosmos-sdk
disable ClaimMsg after FinalSunsetFork
n/a
* n/a
n/a
> chore: update cosmos-sdk

- go.mod
- go.sum
This pr is to fix the issue that no tag of relayer fee in `handleMsgSideChainStakeMigration`
* add missing tag of relayer fee in `handleMsgSideChainStakeMigration`
> fix: add missing tag of relayer fee in `handleMsgSideChainStakeMigration`

- go.mod
- go.sum
update cosmos-sdk to fix refundStake issue
https://github.com/bnb-chain/bnc-cosmos-sdk/pull/378/files
https://github.com/bnb-chain/bnc-cosmos-sdk/pull/379/files
n/a
* n/a
n/a
n/a
> chore: update cosmos-sdk to fix refundStake issue

- plugins/tokens/plugin.go
chore: add logs to refund tokens
Added more logs to more easily monitor processes
n/a
* tokens
n/a
n/a
> chore: add logs to refund tokens

- app/app.go
- cmd/bnbcli/main.go
- plugins/migrate/client/cli/commands.go
- plugins/migrate/client/cli/tx.go
- plugins/migrate/msg.go
- plugins/migrate/wire.go
- plugins/recover/client/cli/tx.go
feat: implement cmd to sign validator ownership
bsc validator on bc can sign their sigs to prove the ownership to the new operator address on bsc after bc-fusion
```bash
./build/tbnbcli validator-ownership sign-validator-ownership --bsc-operator-address 0x45737bAf95D995a963ab3a7c9AC66fC7A63ad76E --from test1 --chain-id Binance-Chain-Ganges
```
* cmd
n/a
n/a
> feat: implement cmd to sign validator ownership

- app/app.go
- common/utils/times.go
fix: change BreatheBlockInterval config to time period
In order to match the breathing block judgment of BSC, it is necessary to change the original judgment based on block height to time judgment.
n/a
* config
n/a
n/a
> fix: change BreatheBlockInterval config to time period

- CHANGELOG.md
- asset/mainnet/app.toml
- version/version.go
This PR add the FirstSunset height to mainnet config.
The target fork time is `2024/4/15/ 06:00:00 UTC+0`(1713160800)
Current Block time: `2024/4/1 03:25:38 UTC+0`(1711941938) -> https://explorer.bnbchain.org/block/372822440
Avg Block Time: 19s/11 ~= 1.73s
Target Fork Block Height: (1713160800 - 1711941938)/1.73 + 372822440 ~= `373526985`
n/a
n/a
n/a
n/a
> feat: enable FirstSunset on mainnet

- CHANGELOG.md
- asset/testnet/app.toml
This just enable the upgrade height for Second Sunset of BNB Beacon Chain testnet.
prepare for release v0.10.21
No
None
...
> release: release v0.10.21

- asset/testnet/app.toml
Update testnet second sunset hardfork height:
2024-06-12 14:00:00 height: 54188856 https://testnet-explorer.bnbchain.org/block/54188856
2024-06-11 14:00:00 height: 54148202 https://testnet-explorer.bnbchain.org/block/54148202
2024-06-21 14:00:00 height: 54188856 + 9 * (54188856 - 54148202) = 54554742
update second sunset hardfork height for testnet
NA
* app.toml
> chore: update testnet second sunset hardfork height

- CHANGELOG.md
- asset/mainnet/app.toml
- version/version.go
This is release pr to enable `Second Sunset Hardfork` on BC mainnet.
June 26, 14:00 height: 377148750 
June 25, 14:00 height: 377097970
July 14, 14:00 expect height: 377148750 + (377148750 - 377097970) * 18 = 378,062,790
NA
* hardfork height
> release: release v0.10.22

- CHANGELOG.md
- asset/testnet/app.toml
- version/version.go
Release for the Final Sunset Fork of Beacon Chain testnet.
Jul 16 14:00 height: 55569662 https://testnet-explorer.bnbchain.org/block/55569662
Ju1 15 14:00 height: 55529098 https://testnet-explorer.bnbchain.org/block/55529098
Aug 1 14:00 expected height: 55569662 + (55569662 - 55529098) * 16  = 56,218,686
NA
* app.toml
> release: release v0.10.23
